#!/usr/bin/env node
// Reusable Markdown -> Farisium BlogSection[] converter.
//
// Usage:
//   node scripts/md-to-blog.mjs <input.md> [output.txt]
//
// Converts a plain/Markdown article body into the BlogSection[] object array
// format used by lib/blog.ts. The output is written to stdout (or <output.txt>).
//
// Supports:
//   ## Heading  -> { type:'heading', level:2 }
//   ### Heading -> { type:'heading', level:3 }
//   * item / - item / 1. item -> { type:'list', items:[...] } (consecutive, grouped)
//   > quote     -> plain paragraph text (renderer has no blockquote styling)
//   ---         -> ignored (section divider; headings already delimit sections)
//   blank-line-separated text -> { type:'paragraph' }
//
// Markdown emphasis markers (**text**, *text*, `text`, __text__) are stripped
// because the renderer treats body as plain text. The only supported inline
// syntax is the internal link form [[label](/path)] which the renderer handles.
//
// Images, blockquote styling, and closing CTA are NOT auto-generated from
// Markdown; add them manually after conversion to match the article's intended
// SVG placement and SEO structure.

import { readFileSync, writeFileSync } from 'node:fs'

const input = process.argv[2]
const output = process.argv[3]

if (!input) {
  console.error('Usage: node scripts/md-to-blog.mjs <input.md> [output.txt]')
  process.exit(1)
}

const raw = readFileSync(input, 'utf8')

// Split into logical blocks on blank lines, keeping a marker of adjacent
// grouping for list detection.
const blocks = raw
  .replace(/\r\n/g, '\n')
  .split(/\n{2,}/)
  .map((b) => b.split('\n').filter((l) => l.trim() !== ''))

const sections = []

function isHeading(line) {
  return /^(#{1,6})\s+/.test(line)
}

function headingLevel(line) {
  const m = line.match(/^(#{1,6})\s+/)
  return m ? m[1].length : 0
}

function isListLine(line) {
  return /^(\s*[-*+]\s+|\s*\d+\.\s+)/.test(line)
}

function stripListMarker(line) {
  return line.replace(/^\s*(?:[-*+]\s+|\d+\.\s+)/, '').trim()
}

function cleanInline(text) {
  // Remove unsupported Markdown emphasis and code markers (plain-text body).
  return text
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/^\s*>\s?/, '')
}

for (const block of blocks) {
  if (block.length === 0) continue

  // Heading block (single line)
  if (block.length === 1 && isHeading(block[0])) {
    const level = headingLevel(block[0])
    if (level === 2 || level === 3) {
      sections.push({
        type: 'heading',
        level,
        text: block[0].replace(/^#{1,6}\s+/, '').trim(),
      })
    }
    continue
  }

  // Consecutive list lines -> grouped list
  if (block.every(isListLine)) {
    sections.push({
      type: 'list',
      items: block.map((l) => cleanInline(stripListMarker(l))),
    })
    continue
  }

  // Otherwise join as paragraph text (blockquote `>` markers are converted to
  // plain prose; the renderer has no dedicated blockquote styling).
  if (block.length === 1) {
    sections.push({ type: 'paragraph', text: cleanInline(block[0].trim()) })
    continue
  }

  // A multi-line non-list block (e.g. blockquoted phrase followed by prose) is
  // emitted as one or more paragraphs preserving the original line breaks.
  for (const line of block) {
    const text = cleanInline(line.trim())
    if (text) sections.push({ type: 'paragraph', text })
  }
}

const out = sections
  .map((s) => {
    if (s.type === 'heading') {
      return `    { type: 'heading', level: ${s.level}, text: ${JSON.stringify(s.text)} },`
    }
    if (s.type === 'list') {
      const items = s.items.map((t) => `        ${JSON.stringify(t)},`).join('\n')
      return `    {\n      type: 'list',\n      items: [\n${items}\n      ],\n    },`
    }
    return `    { type: 'paragraph', text: ${JSON.stringify(s.text)} },`
  })
  .join('\n')

const result = `  // GENERATED by scripts/md-to-blog.mjs — insert images/CTA and review before committing.\n${out}\n`

if (output) writeFileSync(output, result)
process.stdout.write(result)
